### ISSUE TITLE
What is the difference of Certlint and Cablint?

### ISSUE THREAD

**Issue by poliveiragmail** [certlint/certlint#8]
From the output below Certlint perform less checks than Cablint:

/opt/certlint$ ruby -I lib:ext bin/cablint /mnt/c/Temp/Zlint/Cert-1.cer
W: Microsoft extension 1.3.6.1.4.1.311.20.2 treated as opaque extension Cert-1.cer
I: TLS Server certificate identified    Cert-1.cer
E: BR certificates must include an HTTP URL of the OCSP responder       Cert-1.cer
W: BR certificates should include an HTTP URL of the issuing CA's certificate   Cert-1.cer
E: BR certificates must include certificatePolicies     Cert-1.cer
E: BR certificates with CRL Distribution Point must include HTTP URL    Cert-1.cer

/opt/certlint$ ruby -I lib:ext bin/certlint certs/Cert-1.der
W: Microsoft extension 1.3.6.1.4.1.311.20.2 treated as opaque extension Cert-1.der

Additionally Certlint expects Binary certificate format and Cablint Base64 format.

Is there something else?

**Comment by mpalmer** [comment]
Certlint verifies against the IETF (and other) standards for a well-formed certificate.  Cablint verifies conformance to the CA/Browser Forum's Baseline Requirements, which are rules that several common trust store programs have collectively agreed need to be followed if you want your CA to be in their programs.
